### ISSUE TITLE
Embedded paid content without purchase notification

### ISSUE THREAD

**Issue by michaelmitnick** [OdyseeTeam/odysee-frontend#1345] opened 2022-04-17 15:01 UTC
Paid content that is embedded on other pages does not notify the user (active session on Odysee) that it is paid content and is automatically purchased. The content is not shown as paid, only as free content. It has been tested on Firefox and Brave, without notification of any kind.

The report has been submitted by a user and I have tested it.

Links from paid and embedded content.

1. https://actualidad.rt.com/actualidad/427176-zelenski-acuerdo-paz-rusia
2. https://odysee.com/@ActualidadRT:9/azov_Zelenski:c

**Comment by infinite-persistence** [comment] 2022-04-18 00:50
Related/duplicate of:
- #677 
- #678

**Comment by tzarebczan** [comment] 2022-04-18 04:35
We should at least fix the bug where it auto pays. Funny.. it showed watch in Odysee button, but still purchased it.

**Closed** 2022-04-18 06:12 UTC
Labels: bug, consider soon
